Initial commit of SGS version.  Eliminated boot.img and apps2sd files, modified others, cleaned up the menu.

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -1,6 +1,6 @@
 #!/bin/bash
  
-version=0.126
+version=0.1
 
 chmod 755 scripts/*
 scripts/init_kitchen
@@ -19,45 +19,70 @@ do
 
  echo 
  echo "============================================================"
- echo " HTC Android Kitchen $version - by dsixda (xda-developers.com)"
+ echo " SGS Android Kitchen $version - by RMGeren (xda-developers.com)"
+ echo
+ echo "        Based on the HTC Android Kitchen - by dsixda" 
  echo "============================================================"
  echo
+ echo " 81 - Get stock ROMs"
  echo "  1 - Set up working folder from ROM"
  echo "  2 - Add root permissions"
  echo "  3 - Add BusyBox"
  echo "  4 - Disable boot screen sounds"
- echo "  5 - Add wireless tethering"
- echo "  6 - Zipalign all *.apk files to optimize RAM usage"
- echo "  7 - Change wipe status of ROM"
- echo "  8 - Change name of ROM"
- echo "  9 - Check update-script for errors"
- echo " 10 - Show working folder information"
+ echo "  5 - Zipalign all *.apk files to optimize RAM usage"
+ echo "  6 - Change wipe status of ROM"
+ echo "  7 - Change name of ROM"
+ echo "  8 - Check update-script for errors"
+ echo "  9 - Show working folder information"
+ echo " 10 - Set up working folder for Samsung leak"
+ echo " 11 - Deodex files in your ROM"
+ echo " 12 - Add task killer tweak for speed (stock ROM only)"
+ echo " 13 - Add /data/app functionality"
+ echo " 14 - Add Nano text editor + sysro/sysrw"
+ echo " 15 - Add Bash (command shell)"
+ echo " 16 - Add /etc/init.d scripts"
+ echo " 17 - Add custom boot animation functionality"
+ echo " 18 - Sign APK file(s)"
+ echo " 19 - Convert update-script or updater-script"
+ echo " 20 - Run plugin scripts"
+ echo " 21 - Add kernel to ROM"
+ echo " 22 - Add modem to ROM" 
  echo 
- echo "  0 - ADVANCED OPTIONS"
  echo " 99 - Build ROM from working folder"
  echo
  echo "  u - Update/About kitchen"
  echo "  x - Exit"
- echo
- echo 
+ echo ""
  echo -n "Enter option: "
  read opt
  case $opt in
+  81) scripts/get_stock_roms; continue;;
    1) clear; scripts/check_rom; continue;;
    2) scripts/do_root; continue;;
    3) scripts/add_busybox show_help;;
    4) scripts/disable_sounds;;
-   5) scripts/add_tether;;
-   6) scripts/do_zipalign;;
-   7) scripts/change_wipe;;
-   8) scripts/change_rom_name;;
-   9) scripts/verify_update_script; continue;;
-   10) scripts/show_rom_info;;
-   0) scripts/menu_advanced $version; continue;;
-   99) scripts/build_rom;;
-   u) scripts/about $version; continue;;
-   x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
-   *) echo "Invalid option"; continue;;
+   5) scripts/do_zipalign;;
+   6) scripts/change_wipe;;
+   7) scripts/change_rom_name;;
+   8) scripts/verify_update_script; continue;;
+   9) scripts/show_rom_info;;
+  10) clear; scripts/choose_rom_rfs; continue;;
+  11) scripts/do_deodex; continue;; 
+  12) scripts/task_killer;;
+  13) scripts/add_data_app show_help;;
+  14) scripts/add_nano show_help;;
+  15) scripts/add_bash show_help;;
+  16) scripts/add_busybox_run_parts show_help;;
+  17) scripts/add_custom_boot_anim;;
+  18) scripts/sign_apks; continue;;
+  19) scripts/update_script_convert_menu; continue;;
+  20) scripts/run_plugins; continue;;
+  21) scripts/add_kernel_to_update_script;;
+  22) scripts/add_modem_to_update_script;;
+  99) scripts/build_rom;;
+  u) scripts/about $version; continue;;
+  x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
+  *) echo "Invalid option"; continue;;
  esac
 
   scripts/press_enter
diff --git a/scripts/img_files_to_working_folder b/scripts/img_files_to_working_folder
--- a/scripts/img_files_to_working_folder
+++ b/scripts/img_files_to_working_folder
@@ -8,11 +8,6 @@ then
 
 else
 
-  current_dir=`pwd`
-  dest_dir=$current_dir/original_update
-  scripts/check_no_bootimg $dest_dir
-
-
   #
   # Check for system.img and boot.img in original_update  
   #
@@ -70,85 +65,72 @@ cp tools/update_files/update-script $build_dir/META-INF/com/google/android/
 
 
 #
-# Check for location of Android header in boot.img so that it can be
-# added to working folder correctly
+# unyaffs
 #
-scripts/check_bootimg_header
+echo
 
-
-#
-# Check for YAFFS/EXT3
-#
-
-system_dir=$build_dir/system
-
-scripts/check_if_img_yaffs $system_dir system.img
-
-is_yaffs=$?
-
-if [ "$is_yaffs" == "1" ]
+if [ `uname | grep CYGWIN` ]
 then
-
-  if [ `uname | grep CYGWIN` ]
-  then
-    unyaffs_file=unyaffs.exe
-  else
-    unyaffs_file=unyaffs
-  fi
-    
-  scripts/compile_unyaffs
-  if [ "$?" == "1" ]
-  then
-    exit 0
-  fi
-
-  echo
-  echo Extracting contents of system.img ...
-  cd $system_dir
-  ../../tools/unyaffs_files/$unyaffs_file system.img 2>/dev/null
-
+  unyaffs_file=unyaffs.exe
 else
-
-  echo
-  echo "'EXT3' FILE FORMAT DETECTED IN ROM"
-  echo
-
-  cd $system_dir
-
-  # Get full path
-  system_dir=`pwd`
-
+  unyaffs_file=unyaffs
+fi
+  
+if [ -e tools/unyaffs_files/$unyaffs_file ]
+then
+  echo Found $unyaffs_file
+else
+  echo "Compiling unyaffs ..."
+  cd tools/unyaffs_files
+  gcc -o unyaffs unyaffs.c
   cd ../..
-  scripts/extract_ext3_img $system_dir system.img
-  cd $system_dir
 
+  if [ -e tools/unyaffs_files/$unyaffs_file ]
+  then
+    echo unyaffs successfully compiled
+  else
+    echo "Error: unyaffs not successfully compiled!"
+    exit 1
+  fi
 fi
 
+echo
+echo Extracting contents of system.img ...
+cd $build_dir/system
+res=`../../tools/unyaffs_files/$unyaffs_file system.img 2>/dev/null`
 
+err_code=$?
 check_dump=`ls unyaffs*stackdump* 2>/dev/null`
-rm -f system.img
+
+rm system.img
 cd ..
 
 if [ "$check_dump" != "" ]
 then
   echo
-  echo "Error:  stackdump file found under /system folder due to incompatibility"
-  echo "        with unyaffs."
+  echo "Error:  unyaffs - stackdump file found under /system folder.  The file"
+  echo "        format used in the .img file may not be supported."
   exit 1
 fi
 
 if [ ! -d system ]
 then
   echo
-  echo "Error:  no /system folder found!"
+  echo "Error: no /system folder found!"
   exit 1
 fi
-
+ 
 if [ "`ls system`" == "" ]
 then
   echo 
-  echo "Error:  /system folder is empty!"
-  echo
+  echo "Error: /system folder is empty!"
+  
+  if [ "$err_code" == 139 ]
+  then
+    echo "Unfortunately unyaffs cannot open this system.img.  The file format"
+    echo "used in the .img file may not be supported."
+  fi
+
   exit 1
 fi
 
@@ -158,7 +140,6 @@ scripts/fix_update_script
 # Modify the update-script with features found in Nandroid backup
 scripts/fix_update_script_with_features
 
-scripts/remove_recovery
 
 echo
 echo Listing of $build_dir:
diff --git a/scripts/zip_file_to_working_folder b/scripts/zip_file_to_working_folder
--- a/scripts/zip_file_to_working_folder
+++ b/scripts/zip_file_to_working_folder
@@ -1,9 +1,3 @@
-#
-# This file has two arguments:
-# $1 = file name (mandatory)
-# $2 = "kernel_only" (optional)
-#
-
 
 update_file=$1
  
@@ -38,39 +32,20 @@ cp original_update/$update_file $build_dir
 echo
 echo "Extracting ROM ..."
 cd $build_dir
-unzip -q $update_file -x recovery.img recovery_signed.img userdata.img radio.img rcdata.img splash1.nb0 splash2.nb0 android-info.txt 2>/dev/null
+unzip -q $update_file
+
 
 if [ "$?" == "9" ]
 then
   echo
-  echo "Error: Cannot extract ROM!"
+  echo "Error extracting ROM"
   cd ..
+  scripts/press_enter
   exit 1
 fi
 
 
 rm -f $update_file
-
-
-#
-# Look for the boot.img and add a fake one if necessary
-#
-
-build_dir=`pwd`
-cd ..
-scripts/check_no_bootimg $build_dir
-cd $build_dir
-
-if [ ! -e boot.img ]
-then
-  echo "Error: No boot.img found, cannot continue"
-  echo
-  cd ..
-  echo "Removing $build_dir ..."
-  rm -rf $build_dir
-  echo
-  exit 1
-fi
 
 
 #
@@ -81,12 +56,6 @@ if [ "`find . -maxdepth 1 | grep .img | grep -c system_`" == "1" ]
 then
   mv system_*.img system.img
 fi 
-
-if [ "`find . -maxdepth 1 | grep .img | grep -c boot_`" == "1" ]
-then
-  mv boot_*.img boot.img
-fi 
-
 
 if [ -e system.img ]
 then
@@ -111,6 +80,12 @@ then
     cd ..
     scripts/img_files_to_working_folder no_create
     exit $?
+
+  else
+    echo "Error: No boot.img found"
+    echo
+    cd ..
+    exit 1
   fi
 fi
 
@@ -132,27 +107,6 @@ then
   exit 1
 
 else
-
-  #
-  # Check for NAND ROM - convert the boot folder to boot.img
-  #
-  if [ ! -e boot.img ]
-  then
-    if [ -e boot/initrd.gz ] && [ -e boot/zImage ]
-    then
-      echo
-      echo "NAND ROM detected, converting boot folder to boot.img for"
-      echo "compatibility with kitchen (will be converted back when"
-      echo "ROM is built) ..."
-
-      cd ..
-      scripts/ensure_nand_extracted no_clear
-      scripts/build_boot_img
-      cd WORKING_*
-    fi
-
-  fi
-
 
   #
   # Remove bad symlinks (*.lnk)
@@ -181,75 +135,63 @@ else
 
   cd ..
   echo
+  scripts/check_no_update_script
+  cd WORKING_*
 
-  if [ "$2" != "kernel_only" ]
+  cd META-INF/com/google/android
+
+
+  #
+  # Check for extra files / folders; e.g in OTA update
+  #
+
+  if [ -e updater-script ] && [ -e update-script ]
   then
-
-    scripts/check_no_update_script
-    error_code=$?
-    cd WORKING_*
-
-    cd META-INF/com/google/android
-
-
-    #
-    # Check for extra files / folders; e.g in OTA update
-    #
-
-    if [ -e updater-script ] && [ -e update-script ]
+    echo
+    echo "Warning: Both updater-script and update-script are found."
+    echo -n "Remove updater-script (y/n)? (default: y) "
+    read enterRemove
+    if [ "$enterRemove" != "n" ]
     then
-      echo
-      echo "Warning: Both updater-script and update-script are found."
-      echo -n "Remove updater-script (y/n)? (default: y) "
-      read enterRemove
-      if [ "$enterRemove" != "n" ]
-      then
-        echo "Removing updater-script"
-        rm -f updater-script
-      else
-        echo "Not removing updater-script"
-      fi
+      echo "Removing updater-script"
+      rm -f updater-script
+    else
+      echo "Not removing updater-script"
     fi
-    if [ -e update-binary ] && [ -e update-script ]
+  fi
+  if [ -e update-binary ] && [ -e update-script ]
+  then
+    echo
+    echo "Warning: Both update-binary and update-script are found."
+    echo -n "Remove update-binary (y/n)? (default: y) "
+    read enterRemove
+    if [ "$enterRemove" != "n" ]
     then
-      echo
-      echo "Warning: Both update-binary and update-script are found."
-      echo -n "Remove update-binary (y/n)? (default: y) "
-      read enterRemove
-      if [ "$enterRemove" != "n" ]
-      then
-        echo "Removing update-binary"
-        rm -f update-binary
-      else
-        echo "Not removing update-binary"
-      fi
+      echo "Removing update-binary"
+      rm -f update-binary
+    else
+      echo "Not removing update-binary"
     fi
-
-
-    if [ -e update-script ]
-    then
-      #
-      # Remove some comments to prevent common issues with kitchen
-      #
-      sed -i \
-        -e 's/#set_perm[^\n]*[\n]*//g' \
-        -e 's/#write[^\n]*[\n]*//g' \
-        update-script
-    fi
-
-    rm -rf update-script.bak
-    cd ../../../../..
-
-    scripts/remove_recovery
   fi
 
-  echo
-  echo "Listing of META-INF/com/google/android:"
 
-  cd WORKING_*
-  cd META-INF/com/google/android
-  ls -l 
+  #
+  # Remove some comments to prevent common issues with kitchen
+  #
+  sed -i \
+    -e 's/#set_perm[^\n]*[\n]*//g' \
+    -e 's/#write[^\n]*[\n]*//g' \
+    update-script
+
+  rm -rf update-script.bak
+
+  echo
+  echo "Contents of META-INF/com/google/android:"
+  ls -l
+
   cd ../../../../..
+
+  scripts/remove_recovery
 
 fi
 
@@ -269,14 +211,6 @@ echo
 if [ -d system ]
 then
   echo "Finished setting up working folder!"
-
-  if [ "$error_code" == "2" ]
-  then
-    exit 1
-  else
-    exit 0
-  fi
-
 else
   echo "Error: Setup failed"
   cd ..
@@ -285,4 +219,4 @@ else
 fi
 
 cd ..
-
+scripts/press_enter
